//! Benchmarked contender Lambda: archives S3 objects under a prefix into one flat ZIP.
//!
//! Pipeline: list the source objects, run the pure `engine::plan` planner to decide the
//! copy-part fast path vs the streaming fallback, then execute via `aws::assemble`
//! (server-side UploadPartCopy for large objects, streaming only the small ones) or the
//! minimal `aws::stream_fallback` for degenerate inputs.
//!
//! The entry point is generated by `awssdk_instrumentation::make_lambda_runtime!`, which
//! wires the Lambda runtime and an S3 client accessible via `s3()`.

mod aws;
mod engine;

use std::sync::Arc;

use awssdk_instrumentation::lambda::{LambdaError, LambdaEvent};
use serde::Deserialize;
use tracing::{error, info};

use crate::engine::plan::{FileId, SingleRouting, SourceFile, plan_single_mpu};

/// Lambda event payload describing one archiving job.
#[derive(Debug, Deserialize, Clone)]
struct JobInfo {
    bucket_name: Arc<str>,
    files_prefix: Arc<str>,
    archive_key: Arc<str>,
}

/// List every object under `{files_prefix}/`, returning a `SourceFile` per object with a
/// stable id, full key, bare name (key minus prefix), and size.
async fn list_source_files(
    bucket: String,
    files_prefix: &str,
) -> Result<Vec<SourceFile>, LambdaError> {
    let s3_prefix = format!("{files_prefix}/");
    let mut paginator = s3()
        .list_objects_v2()
        .bucket(bucket)
        .prefix(s3_prefix.clone())
        .into_paginator()
        .send();

    let mut out = Vec::new();
    let mut next_id: u32 = 0;
    while let Some(page) = paginator.next().await {
        let page = page?;
        for obj in page.contents.into_iter().flatten() {
            let Some(key) = obj.key else { continue };
            let Some(size) = obj.size else { continue };
            if key == s3_prefix {
                continue;
            }
            if let Some(name) = key.strip_prefix(&s3_prefix) {
                if name.is_empty() {
                    continue;
                }
                out.push(SourceFile {
                    id: FileId(next_id),
                    name: name.to_string(),
                    size: size as u64,
                });
                next_id += 1;
            }
        }
    }
    Ok(out)
}

/// Lambda handler: list -> plan -> assemble (fast path) | stream_fallback.
async fn handler(event: LambdaEvent<JobInfo>) -> Result<(), LambdaError> {
    let JobInfo {
        bucket_name,
        files_prefix,
        archive_key,
    } = event.payload;

    info!(%bucket_name, %files_prefix, %archive_key, "contender invoked");

    let files = list_source_files(bucket_name.to_string(), &files_prefix).await?;
    info!(count = files.len(), "listed source files");

    match plan_single_mpu(files) {
        SingleRouting::SingleMpu(p) => {
            info!(parts = p.parts.len(), "single-MPU fast path");
            if let Err(e) = aws::assemble::assemble(
                &s3(),
                bucket_name.to_string(),
                files_prefix.to_string(),
                archive_key.to_string(),
                p,
            )
            .await
            {
                error!(%e, "single-MPU assemble failed");
                return Err(Box::new(e));
            }
        }
        SingleRouting::Fallback => {
            info!("streaming fallback path");
            if let Err(e) = aws::stream_fallback::run(
                &s3(),
                bucket_name.to_string(),
                archive_key.to_string(),
                files_prefix.to_string(),
            )
            .await
            {
                error!(%e, "stream fallback failed");
                return Err(Box::new(e));
            }
        }
    }

    info!("archive complete");
    Ok(())
}

awssdk_instrumentation::make_lambda_runtime!(
    handler,
    trigger = awssdk_instrumentation::lambda::layer::OTelFaasTrigger::Other,
    s3() -> aws_sdk_s3::Client
);
